POST http://localhost:6000/products
Content-Type: application/json

{
    "nameProduct":"Es Jeruk",
    "categories":"Minuman",
    "madeIn":"Pontianak"
}
###
DELETE http://localhost:6000/products/6758478d7ca2c49a55b90d60
###

PATCH http://localhost:6000/products/6758480f7ca2c49a55b90d6a
Content-Type: application/json

{
    "madeIn":"Semarang"
}
###
GET http://localhost:6000/products/